SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS public_data;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS specifications;
DROP TABLE IF EXISTS specifications;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;